{
 "title": "CRDB Console: Runtime ",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(sys_uptime{job=\"cockroachdb\"},cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{job=\"cockroachdb\",cluster=\"$cluster\"},instance)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Live Node Count",
   "type": "graph",
   "description": "The number of live nodes in the cluster.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "nodes" }
   ],
   "targets": [
    {
     "expr": "min(liveness_livenodes{cluster=\"$cluster\",job=\"cockroachdb\",instance=~\"$node\"})",
     "legendFormat": "Live Nodes"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory in use across all nodes:\nRSS  \nTotal memory in use by CockroachDB\n\nGo Allocated  \nMemory allocated by the Go layer\n\nGo Total  \nTotal memory managed by the Go layer\n\nC Allocated  \nMemory allocated by the C layer\n\nC Total  \nTotal memory managed by the C layer",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "memory usage" }
   ],
   "targets": [
    {
     "expr": "sum(sys_rss{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "Total memory (RSS)"
    },
    {
     "expr": "sum(sys_cgo_allocbytes{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "Go Allocated"
    },
    {
     "expr": "sum(sys_go_totalbytes{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "Go Total"
    },
    {
     "expr": "sum(sys_go_allocbytes{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "CGo Allocated"
    },
    {
     "expr": "sum(sys_cgo_totalbytes{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "CGo Total"
    }
   ]
  },
  {
   "title": "Goroutine Count",
   "type": "graph",
   "description": "The number of Goroutines across all nodes. This count should rise and fall based on load.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "goroutines" }
   ],
   "targets": [
    {
     "expr": "sum(sys_goroutines{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "Goroutine Count"
    }
   ]
  },
  {
   "title": "Runnable Goroutines per CPU",
   "type": "graph",
   "description": "The number of Goroutines waiting for CPU. This count should rise and fall based on load.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "goroutines" }
   ],
   "targets": [
    {
     "expr": "sys_runnable_goroutines_per_cpu{job=\"cockroachdb\",cluster=~\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC Runs",
   "type": "graph",
   "description": "The number of times that Go’s garbage collector was invoked per second across all nodes.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "runs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sys_gc_count{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "GC Runs"
    }
   ]
  },
  {
   "title": "GC Pause Time",
   "type": "graph",
   "description": "The amount of processor time used by Go’s garbage collector per second across all nodes. During garbage collection, application code execution is paused.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ns", "label": "pause time" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sys_gc_pause_ns{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "GC Pause Time"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ns", "label": "cpu time" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sys_cpu_user_ns{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "User CPU Time"
    },
    {
     "expr": "sum(rate(sys_cpu_sys_ns{job=\"cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Sys CPU Time"
    }
   ]
  },
  {
   "title": "Clock Offset",
   "type": "graph",
   "description": "Mean clock offset of each node against the rest of the cluster.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ns", "label": "offset" }
   ],
   "targets": [
    {
     "expr": "clock_offset_meannanos{job=\"cockroachdb\",instance=~\"$node\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}